# Generated by Django 6.0.1 on 2026-02-01 17:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="employee",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="employee",
            name="last_name",
            field=models.CharField(default=1, max_length=200),
            preserve_default=False,
        ),
    ]
