# Generated by Django 6.0.1 on 2026-02-04 05:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="address",
            name="permanent_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="address",
            name="present_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="national_address",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="address",
            name="room_address",
            field=models.TextField(blank=True, null=True),
        ),
    ]
