# Generated by Django 6.0.1 on 2026-02-04 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_address_permanent_address_address_present_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vehicle",
            name="employee",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="backend.employee"
            ),
        ),
    ]
