# Generated by Django 6.0.1 on 2026-04-27 08:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0002_category_transport_workplace"),
    ]

    operations = [
        migrations.AddField(
            model_name="employment",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employments",
                to="backend.category",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="transport",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employments",
                to="backend.transport",
            ),
        ),
        migrations.AddField(
            model_name="employment",
            name="workplace",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="employments",
                to="backend.workplace",
            ),
        ),
    ]
