# Generated by Django 6.0.1 on 2026-02-01 18:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_employee_user"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="nationality",
            name="abbreviation",
        ),
    ]
