# Generated by Django 6.0.1 on 2026-02-04 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0003_alter_vehicle_employee"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="vehiclehandover",
            options={"ordering": ["-handover_date", "-created_at"]},
        ),
        migrations.AddField(
            model_name="vehiclehandover",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
    ]
