# Generated by Django 6.0.1 on 2026-04-30 15:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0005_licensetype_drivinglicense_license_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="company",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicles",
                to="backend.company",
            ),
            preserve_default=False,
        ),
    ]
