# Generated by Django 6.0.1 on 2026-04-30 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_vehicle_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleassign",
            name="kilometers",
            field=models.PositiveIntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleassign",
            name="assigned_date",
            field=models.DateTimeField(),
        ),
    ]
