# Generated by Django 6.0.1 on 2026-02-08 06:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0006_uniform_uniformstock_uniformissuance_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="uniformclearance",
            name="cleared_by",
        ),
        migrations.RemoveField(
            model_name="uniformissuance",
            name="issued_by",
        ),
    ]
