# Generated by Django 6.0.1 on 2026-05-02 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_vehicleassign_trafic_status_uniformcategory"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleassign",
            name="unassigned_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="vehicleassign",
            name="status",
            field=models.CharField(
                choices=[
                    ("ASSIGNED", "Assigned"),
                    ("UNASSIGNED", "Unassigned"),
                    ("RETURNED", "Returned"),
                ],
                default="ASSIGNED",
                max_length=20,
            ),
        ),
    ]
