# Generated by Django 6.0.1 on 2026-02-08 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0008_remove_vehicleinstallment_vehicle_vehiclepurchase_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleinstallment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Cash"),
                    ("CARD", "Card"),
                    ("ONLINE", "Online"),
                    ("BANK_TRANSFER", "Bank Transfer"),
                    ("OTHER", "Other"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vehicleinstallment",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pending"),
                    ("PAID", "Paid"),
                    ("OVERDUE", "Overdue"),
                    ("CANCELLED", "Cancelled"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
    ]
