# Generated by Django 6.0.1 on 2026-02-08 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_vehicleinstallment_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="chassee_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="vehicle",
            name="engine_no",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name="vehicle",
            name="plate_no",
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name="vehiclepurchase",
            name="employee",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="vehicle_purchases",
                to="backend.employee",
            ),
        ),
    ]
