# Generated by Django 6.0.1 on 2026-05-02 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0009_vehicleassign_unassigned_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniform",
            name="categories",
            field=models.ManyToManyField(
                blank=True, related_name="uniforms", to="backend.uniformcategory"
            ),
        ),
    ]
