# Generated by Django 6.0.1 on 2026-02-08 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0010_vehicle_chassee_no_vehicle_engine_no_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="uniformstock",
            name="code",
            field=models.CharField(default=1, max_length=50, unique=True),
            preserve_default=False,
        ),
    ]
