# Generated by Django 6.0.1 on 2026-02-15 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0013_company_employee_company"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicleassign",
            name="status",
            field=models.CharField(
                choices=[("ASSIGNED", "Assigned"), ("RETURNED", "Returned")],
                default="ASSIGNED",
                max_length=20,
            ),
        ),
    ]
