# Generated by Django 6.0.1 on 2026-02-15 06:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("backend", "0014_vehicleassign_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vehicle",
            name="status",
            field=models.CharField(
                choices=[("ACTIVE", "Active"), ("INACTIVE", "Inactive")],
                default="ACTIVE",
                max_length=10,
            ),
        ),
    ]
