# Generated by Django 6.0.1 on 2026-02-18 10:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0016_followup_followupreminder_lead_followup_lead'),
    ]

    operations = [
        migrations.CreateModel(
            name='MailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_mail', models.EmailField(blank=True, max_length=254, null=True)),
                ('to_mail', models.EmailField(db_index=True, max_length=254)),
                ('subject', models.CharField(blank=True, max_length=255, null=True)),
                ('message', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('SENT', 'Sent'), ('FAILED', 'Failed')], default='SENT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'mail_log',
                'ordering': ['-created_at'],
            },
        ),
    ]
