# Generated by Django 6.0.1 on 2026-02-22 06:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0018_leadsource_alter_lead_source_leadstage_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='uniformstock',
            unique_together={('uniform', 'size')},
        ),
    ]
